[package]
name = "embershot"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["bevy_dev_tools", "dynamic_linking"] }
image = "0.25.6"
rand = "0.9.2"
xcap = { version = "0.6.2", features = ["image"] }
